version: '3.8'

services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: 'mc-vanilla'
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.20.1"
      MEMORY: "4G"
      # CF_API_KEY: '$$2a$$10$$XGGBqmPcAn5gwdDT4YOHBONrocGMofjqosaOLhErvo8iAUQ2KP9ES'
      # CF_CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/create-optimized-fabric/files/4486452"
      # CF_SLUG: "create-optimized-fabric"
      ENABLE_ROLLING_LOGS: "true"
    volumes:
      - ./data:/data
    ports:
      - "25565:25565"
    restart: always


